name: Build Arduino Sketch

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "megaTinyCore:megaavr:atxy2"
          platforms: |
            - name: megaTinyCore:megaavr
              source-url: http://drazzy.com/package_drazzy.com_index.json
          sketch-paths: |
            - src
